global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  # Prometheus kendisi
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js Application
  - job_name: 'yoga-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'

  # PostgreSQL (pgexporter gerekli)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['db:5432']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
